"use client";
import { useEffect, useRef, useState } from "react";
import { api, post, API_BASE, type CaseView, type Draft } from "@/lib/api";
import { Badge, Button, Card, Empty, KV, fmtDate } from "@/components/ui";

// ------------------------------------------------------------------ Drafts (human-in-the-loop)
export function DraftPanel({ c, onChange, say, perms }: { c: CaseView; onChange: () => void; say: (m: string, k?: "ok" | "err") => void; perms: string[] }) {
  const [editing, setEditing] = useState<Draft | null>(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [lang, setLang] = useState("en");
  const [busy, setBusy] = useState(false);
  const canApprove = perms.includes("approve_send");

  const gen = async () => { setBusy(true); try { await post(`/cases/${c.id}/draft`, { language: lang }); say("Draft generated (not sent)"); onChange(); } catch (e: any) { say(e.message, "err"); } finally { setBusy(false); } };
  const act = async (path: string, d: Draft, extra: any = {}) => { setBusy(true); try { await post(`/cases/${c.id}/${path}`, { draft_id: d.id, ...extra }); say("Done"); setEditing(null); onChange(); } catch (e: any) { say(e.message, "err"); } finally { setBusy(false); } };

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <Button kind="primary" disabled={busy} onClick={gen}>Generate draft</Button>
        <select value={lang} onChange={(e) => setLang(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="en">English</option><option value="zh">Chinese</option><option value="ms">Malay</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="ko">Korean</option><option value="ar">Arabic</option></select>
        <span className="text-ink-500">AI proposes → you review/edit → {canApprove ? "you approve" : "a supervisor approves"} → send. Nothing is auto-sent.</span>
        {!c.action_required && <Badge className="bg-ink-100 text-ink-700">No reply needed</Badge>}
      </div>
      {c.drafts.length === 0 && <Empty text={c.action_required ? "No draft yet. Click Generate draft." : "Informational case — no reply needed. Generate a draft only if you want to respond."} />}
      {[...c.drafts].reverse().map((d) => (
        <Card key={d.id} title={<span>{d.draft_type.replace(/_/g, " ")} · v{d.version} <Badge className={{ PROPOSED: "bg-accent-bg text-accent-fg", EDITED: "bg-review-bg text-review-fg", APPROVED: "bg-match-bg text-match-fg", SENT: "bg-match text-white", REJECTED: "bg-mismatch-bg text-mismatch-fg" }[d.status] || ""}>{d.status}</Badge></span>}
          right={<span className="text-[11px] text-ink-500">generated by {d.generated_by} · evidence: {d.evidence_refs.join(", ") || "—"}</span>}>
          <KV k="To" v={<span className="font-mono text-xs">{d.to.join(", ")}</span>} />
          <KV k="Requires approval" v={d.requires_external_approval ? "Yes — external recipient" : "No"} />
          {editing?.id === d.id ? (
            <div className="mt-2 space-y-2">
              <input value={subject} onChange={(e) => setSubject(e.target.value)} className="w-full rounded-md border border-ink-200 px-2 py-1 text-sm" />
              <textarea value={body} onChange={(e) => setBody(e.target.value)} rows={12} className="w-full rounded-md border border-ink-200 p-2 font-mono text-xs" />
              <div className="flex gap-2"><Button kind="primary" onClick={() => act("draft/edit", d, { edited_subject: subject, edited_body: body })}>Save edit</Button><Button onClick={() => setEditing(null)}>Cancel</Button></div>
            </div>
          ) : (
            <div className="mt-2">
              <div className="text-sm font-medium">{d.subject}</div>
              <pre className="mt-1 whitespace-pre-wrap rounded-md bg-ink-50 p-3 font-mono text-[11px]">{d.body}</pre>
            </div>
          )}
          {d.status !== "SENT" && d.status !== "REJECTED" && editing?.id !== d.id && (
            <div className="mt-2 flex flex-wrap gap-2">
              <Button onClick={() => { setEditing(d); setSubject(d.subject); setBody(d.body); }}>Edit</Button>
              <Button kind="success" disabled={!canApprove || busy} title={canApprove ? "Approve and send" : "Requires SUPERVISOR/ADMIN"} onClick={() => act("approve", d)}>Approve & send</Button>
              <Button kind="danger" disabled={busy} onClick={() => act("reject", d, { note: "Rejected by reviewer" })}>Reject</Button>
            </div>
          )}
        </Card>
      ))}
    </div>
  );
}

// ------------------------------------------------------------------ Ask AI
const SUGGESTED = ["Why is this a mismatch?", "Which six fields match?", "Show the SI evidence", "Who is the Notify Party?", "Who should review this?", "Summarize this case", "Draft a correction email", "What changed since the last review?", "Translate this email to Chinese", "What policy applies?"];

export function AskPanel({ c, say }: { c: CaseView; say: (m: string, k?: "ok" | "err") => void }) {
  const [q, setQ] = useState("");
  const [log, setLog] = useState<{ q: string; a: any }[]>([]);
  const [busy, setBusy] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [log]);
  const ask = async (question: string) => {
    if (!question.trim()) return; setBusy(true); setQ("");
    try { const a = await post(`/cases/${c.id}/ask`, { question }); setLog((l) => [...l, { q: question, a }]); } catch (e: any) { say(e.message, "err"); } finally { setBusy(false); }
  };
  return (
    <div className="grid gap-3 lg:grid-cols-[1fr_280px]">
      <div className="flex min-h-[420px] flex-col rounded-xl border border-ink-200 bg-white">
        <div className="flex-1 space-y-3 overflow-auto p-4 scrollbar-thin">
          {log.length === 0 && <div className="text-sm text-ink-500">Grounded assistant — answers only from this case's email, SI, Draft BL, deterministic comparison, audit history and policy. Every answer cites its evidence.</div>}
          {log.map((m, i) => (
            <div key={i}>
              <div className="ml-auto w-fit max-w-[80%] rounded-lg bg-ink-900 px-3 py-2 text-sm text-white">{m.q}</div>
              <div className={`mt-2 w-fit max-w-[90%] rounded-lg border px-3 py-2 text-sm ${m.a.refused ? "border-review bg-review-bg" : "border-ink-200 bg-ink-50"}`}>
                <pre className="whitespace-pre-wrap font-sans">{m.a.answer}</pre>
                <div className="mt-2 flex flex-wrap gap-1">
                  {m.a.citations.map((ct: any, j: number) => <span key={j} title={ct.snippet} className="rounded border border-ink-200 bg-white px-1.5 py-0.5 font-mono text-[10px] text-ink-600">{ct.kind}:{String(ct.ref).slice(0, 28)}</span>)}
                  <span className="ml-auto text-[10px] text-ink-400">{m.a.generated_by} · {m.a.grounded ? "grounded" : "ungrounded"}{m.a.refused ? " · refused" : ""}</span>
                </div>
              </div>
            </div>
          ))}
          <div ref={endRef} />
        </div>
        <form onSubmit={(e) => { e.preventDefault(); ask(q); }} className="flex gap-2 border-t border-ink-100 p-3">
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Ask about this case…" className="flex-1 rounded-md border border-ink-200 px-3 py-2 text-sm" />
          <Button type="submit" kind="primary" disabled={busy}>Ask</Button>
        </form>
      </div>
      <div className="space-y-1">
        <div className="text-[11px] uppercase tracking-wide text-ink-500">Suggested</div>
        {SUGGESTED.map((s) => <button key={s} onClick={() => ask(s)} className="block w-full rounded-md border border-ink-200 bg-white px-2 py-1.5 text-left text-xs hover:bg-ink-50">{s}</button>)}
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ Email (original / translated / side-by-side)
export function EmailPanel({ c }: { c: CaseView }) {
  const [mode, setMode] = useState<"original" | "translated" | "side">("original");
  const [target, setTarget] = useState("en");
  const [tr, setTr] = useState<string | null>(null);
  const e = c.email!;
  const translate = async () => { const r = await post(`/cases/${c.id}/translate`, { target }); setTr(r.translated); };
  return (
    <div className="min-w-0 space-y-3">
      <div className="grid min-w-0 gap-1 rounded-lg bg-ink-50 p-3 text-sm">
        <KV k="From" v={<span className="font-mono text-xs">{e.sender}</span>} /><KV k="Subject" v={e.subject} /><KV k="Received" v={fmtDate(e.received_at)} />
        <KV k="Message ID" v={<span className="font-mono text-xs">{e.id}</span>} /><KV k="Language" v={e.language} /><KV k="Attachments" v={e.attachments.length} />
      </div>
      <div className="flex flex-wrap items-center gap-2 text-xs">
        {(["original", "translated", "side"] as const).map((m) => <Button key={m} kind={mode === m ? "primary" : "default"} onClick={() => setMode(m)}>{m === "side" ? "Side-by-side" : m[0].toUpperCase() + m.slice(1)}</Button>)}
        <select value={target} onChange={(e) => setTarget(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="en">English</option><option value="zh">Chinese</option><option value="ms">Malay</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="ko">Korean</option><option value="ar">Arabic</option></select>
        <Button onClick={translate}>Translate</Button><span className="text-ink-400">stored original is never replaced</span>
      </div>
      <div className={`grid gap-3 ${mode === "side" ? "md:grid-cols-2" : ""}`}>
        {(mode !== "translated") && <pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-lg border border-ink-200 bg-white p-3 font-mono text-xs sm:p-4">{e.body}</pre>}
        {(mode !== "original") && <pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-lg border border-accent/40 bg-accent-bg/20 p-3 font-mono text-xs sm:p-4">{tr ?? "Click Translate."}</pre>}
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ Attachments
export function AttachmentsPanel({ c, onChange, say }: { c: CaseView; onChange: () => void; say: (m: string, k?: "ok" | "err") => void }) {
  const [open, setOpen] = useState<string | null>(null);
  const [kind, setKind] = useState("BL");
  const fileRef = useRef<HTMLInputElement>(null);
  const upload = async () => {
    const f = fileRef.current?.files?.[0]; if (!f) return say("Choose a file", "err");
    const fd = new FormData(); fd.append("file", f); fd.append("kind", kind);
    try { await api(`/cases/${c.id}/upload`, { method: "POST", body: fd }); say("Uploaded — pipeline re-run"); onChange(); } catch (e: any) { say(e.message, "err"); }
  };
  const atts = c.email?.attachments || [];
  return (
    <div className="space-y-3">
      {atts.length === 0 && <Empty text="No attachments on this email." />}
      <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[760px] text-xs">
        <thead className="text-[11px] uppercase text-ink-500"><tr><th className="py-1 text-left">File</th><th className="text-left">Type</th><th className="text-left">Detected as</th><th className="text-left">Extraction</th><th className="text-left">Size / checksum</th><th /></tr></thead>
        <tbody>{atts.map((a) => (
          <tr key={a.id} className="border-t border-ink-100">
            <td className="py-1.5 font-mono">{a.file_name}{a.id === c.si_document_id && <Badge className="ml-1 bg-accent-bg text-accent-fg">SI used</Badge>}{a.id === c.bl_document_id && <Badge className="ml-1 bg-accent-bg text-accent-fg">BL used</Badge>}</td>
            <td>{a.file_type}</td>
            <td>{a.detected_type.replace(/_/g, " ")} <span className="text-ink-400">({a.detection_confidence.toFixed(2)})</span></td>
            <td><Badge className={a.extraction_status === "EXTRACTED" ? "bg-match-bg text-match-fg" : "bg-mismatch-bg text-mismatch-fg"}>{a.extraction_status}</Badge> {a.extraction_confidence > 0 && <span className="text-ink-400">{a.extraction_confidence.toFixed(2)}</span>}{a.is_duplicate_of && <div className="text-[10px] text-review">duplicate of {a.is_duplicate_of}</div>}</td>
            <td className="font-mono text-[10px] text-ink-500">{a.size_bytes} B · {a.checksum.slice(0, 12)}…</td>
            <td className="whitespace-nowrap"><Button kind="ghost" onClick={() => setOpen(open === a.id ? null : a.id)}>{open === a.id ? "Hide text" : "View text"}</Button> <a className="text-accent hover:underline" href={`${API_BASE}/cases/${c.id}/documents/${a.id}/raw`} target="_blank" rel="noreferrer">original ↗</a></td>
          </tr>
        ))}</tbody>
      </table></div>
      {open && <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg border border-ink-200 bg-ink-50 p-3 font-mono text-[11px] scrollbar-thin">{atts.find((a) => a.id === open)?.raw_text || "(no extractable text — unreadable / image-only / empty)"}</pre>}
      <Card title="Upload / re-link a missing document">
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <select value={kind} onChange={(e) => setKind(e.target.value)} className="rounded-md border border-ink-200 px-2 py-1"><option value="SI">Shipping Instruction</option><option value="BL">Draft BL</option><option value="auto">Auto-detect</option></select>
          <input ref={fileRef} type="file" accept=".txt,.pdf,.docx,.xlsx" className="max-w-full text-xs" />
          <Button kind="primary" onClick={upload}>Upload & retry</Button>
          <span className="text-ink-500">Files are parsed to text only — never executed. Blocked types: .exe .bat .js .vbs …</span>
        </div>
      </Card>
    </div>
  );
}

// ------------------------------------------------------------------ Audit
export function AuditPanel({ c }: { c: CaseView }) {
  const [events, setEvents] = useState<any[]>([]);
  const [filter, setFilter] = useState("");
  useEffect(() => { api(`/cases/${c.id}/audit`).then((d) => setEvents(d.events)).catch(() => {}); }, [c.id, c.updated_at]);
  const rows = events.filter((e) => !filter || e.action.includes(filter) || e.actor_type === filter);
  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2 text-xs"><input placeholder="Filter by action or actor (USER/AI/SYSTEM)" value={filter} onChange={(e) => setFilter(e.target.value.toUpperCase())} className="w-72 rounded-md border border-ink-200 px-2 py-1" /><span className="text-ink-500">{rows.length} events · append-only</span></div>
      <div className="overflow-auto rounded-xl border border-ink-200 bg-white scrollbar-thin">
        <table className="w-full text-xs">
          <thead className="bg-ink-50 text-[11px] uppercase text-ink-500"><tr><th className="px-2 py-1.5 text-left">Time</th><th className="px-2 text-left">Actor</th><th className="px-2 text-left">Action</th><th className="px-2 text-left">Before</th><th className="px-2 text-left">After</th><th className="px-2 text-left">Evidence</th><th className="px-2 text-left">Policy</th></tr></thead>
          <tbody>{rows.map((e) => (
            <tr key={e.event_id} className="border-t border-ink-100 align-top">
              <td className="whitespace-nowrap px-2 py-1.5 font-mono text-[10px] text-ink-500">{fmtDate(e.timestamp)}</td>
              <td className="px-2 py-1.5"><Badge className={{ USER: "bg-accent-bg text-accent-fg", AI: "bg-accent-soft text-accent-fg", SYSTEM: "bg-ink-100 text-ink-700" }[e.actor_type as string] || ""}>{e.actor_type}</Badge><div className="text-[10px] text-ink-500">{e.actor_id}</div></td>
              <td className="px-2 py-1.5 font-medium">{e.action}</td>
              <td className="max-w-[220px] px-2 py-1.5 font-mono text-[10px] text-ink-500">{e.before ? JSON.stringify(e.before).slice(0, 160) : ""}</td>
              <td className="max-w-[320px] px-2 py-1.5 font-mono text-[10px] text-ink-700">{e.after ? JSON.stringify(e.after).slice(0, 220) : ""}</td>
              <td className="px-2 py-1.5 font-mono text-[10px] text-ink-500">{e.evidence_ref || ""}</td>
              <td className="px-2 py-1.5 text-[10px] text-ink-500">{e.policy_version}</td>
            </tr>
          ))}</tbody>
        </table>
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ Timeline
const ORDER = ["RECEIVED","SECURITY_CHECK","CLASSIFIED","DOCUMENTS_DETECTED","EXTRACTING","COMPARING","MISMATCH_DETECTED|NO_MISMATCH_DETECTED|WAITING_DOCUMENTS|NO_ACTION_INFO|SECURITY_REVIEW","HUMAN_REVIEW","DRAFT_READY","NOTIFY_PARTY","AWAITING_RESPONSE|ASSIGNED","COMPLETED"];
export function Timeline({ c }: { c: CaseView }) {
  const seen = new Set<string>(["RECEIVED", ...c.trace.map((t) => t.node), c.status]);
  const statusesHit = new Set<string>();
  c.trace.forEach((t) => { if (t.output?.status) statusesHit.add(t.output.status); });
  const stages = ORDER.map((s) => { const opts = s.split("|"); const hit = opts.find((o) => o === c.status) || opts.find((o) => statusesHit.has(o)); return { label: (hit || opts[0]).replace(/_/g, " "), key: s, active: !!hit || (opts.length === 1 && isReached(opts[0], c)) }; });
  return (
    <div className="flex flex-wrap items-center gap-1 text-[10px]">
      {stages.map((s, i) => (
        <div key={s.key} className="flex items-center gap-1">
          <span className={`rounded-full px-2 py-0.5 ${s.label === c.status.replace(/_/g, " ") ? "bg-ink-900 text-white" : s.active ? "bg-accent-bg text-accent-fg" : "bg-ink-100 text-ink-400"}`}>{s.label}</span>
          {i < stages.length - 1 && <span className="text-ink-300">›</span>}
        </div>
      ))}
      <span className="ml-2 text-ink-400">{c.processing_ms} ms pipeline · {seen.size} nodes</span>
    </div>
  );
}
function isReached(stage: string, c: CaseView): boolean {
  const nodes = c.trace.map((t) => t.node);
  const map: Record<string, boolean> = {
    RECEIVED: true, SECURITY_CHECK: nodes.includes("security_precheck"), CLASSIFIED: nodes.includes("intent_classifier"), DOCUMENTS_DETECTED: nodes.includes("attachment_classifier"),
    EXTRACTING: nodes.includes("document_extractor"), COMPARING: nodes.includes("seven_field_comparator"), HUMAN_REVIEW: ["HUMAN_REVIEW","DRAFT_READY","NOTIFY_PARTY","AWAITING_RESPONSE","ASSIGNED","COMPLETED"].includes(c.status) && c.mismatch_count > 0,
    DRAFT_READY: c.drafts.length > 0, NOTIFY_PARTY: ["NOTIFY_PARTY","AWAITING_RESPONSE"].includes(c.status) || c.shared_with.length > 0, COMPLETED: c.status === "COMPLETED",
  };
  return !!map[stage];
}
